# Generated by Django 5.0 on 2024-01-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desigC', models.CharField(max_length=50)),
                ('trashC', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desigP', models.CharField(max_length=250)),
                ('descP', models.CharField(max_length=250)),
                ('typeP', models.CharField(choices=[('matiere', 'Matiere Premiere'), ('produit', 'Produit')], default='matiere', max_length=10)),
                ('qntEnStock', models.PositiveIntegerField()),
                ('trashP', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('zipCode', models.CharField(max_length=50)),
                ('typeUtilisateur', models.IntegerField()),
                ('trashU', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sallaire', models.FloatField()),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='gestion.centre')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='MasAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateMA', models.DateField()),
                ('montantMA', models.FloatField(default=0)),
                ('typeMA', models.CharField(choices=[('abssence', 'Abssence'), ('masrouf', 'Masrouf')], default='abssence', max_length=10)),
                ('empMA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masroufetabssences', to='gestion.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixA', models.FloatField()),
                ('qntA', models.PositiveIntegerField()),
                ('dateA', models.DateTimeField(auto_now=True)),
                ('typeA', models.IntegerField()),
                ('statuA', models.CharField(choices=[('incomplet', 'Incomplet'), ('complet', 'Complet')], default='incomplet', max_length=10)),
                ('trashA', models.SmallIntegerField()),
                ('fournisseurA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.fournisseur')),
                ('prdA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateT', models.DateTimeField()),
                ('qntT', models.PositiveIntegerField()),
                ('centreT', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferts', to='gestion.centre')),
                ('prdT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
            ],
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.utilisateur'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixV', models.FloatField()),
                ('qntV', models.PositiveIntegerField()),
                ('dateV', models.DateTimeField(auto_now=True)),
                ('typeV', models.IntegerField()),
                ('trashV', models.SmallIntegerField()),
                ('centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='gestion.centre')),
                ('clientV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
                ('prdV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateVer', models.DateTimeField(auto_now=True)),
                ('montantVer', models.FloatField()),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='gestion.achat')),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='gestion.vente')),
            ],
        ),
    ]
