# Generated by Django 5.0 on 2024-01-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='typeUtilisateur',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('fournisseur', 'Fournisseur')], default='client', max_length=20),
        ),
    ]
