# Generated by Django 5.0 on 2024-01-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_utilisateur_typeutilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='solde',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
