# Generated by Django 5.0 on 2024-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_client_credit_alter_fournisseur_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='trashA',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achat',
            name='typeA',
            field=models.CharField(choices=[('entièrement', 'Entièrement'), ('partiellement', 'Partiellement')], default='entièrement', max_length=20),
        ),
        migrations.AlterField(
            model_name='centre',
            name='trashC',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='trashP',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='trashU',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vente',
            name='trashV',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vente',
            name='typeV',
            field=models.CharField(choices=[('entièrement', 'Entièrement'), ('partiellement', 'Partiellement')], default='entièrement', max_length=20),
        ),
    ]
