# Generated by Django 5.0 on 2024-01-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_achat_trasha_alter_achat_typea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credit',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='solde',
            field=models.FloatField(default=0, null=True),
        ),
    ]
