# Generated by Django 5.0 on 2024-01-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_client_credit_alter_fournisseur_solde'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='statuV',
            field=models.CharField(choices=[('incomplet', 'Incomplet'), ('complet', 'Complet')], default='incomplet', max_length=10),
        ),
    ]
