# Generated by Django 5.0 on 2024-01-06 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_vente_statuv'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert',
            name='totalT',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='centreT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='gestion.centre'),
        ),
    ]
