# Generated by Django 5.0 on 2024-01-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_transfert_totalt_alter_transfert_centret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='typeUtilisateur',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('fournisseur', 'Fournisseur'), ('employe', 'Employe')], default='client', max_length=20),
        ),
    ]
